spring:
  datasource:
    url: jdbc:mysql://127.0.01:3306/store
    username: root
    password: awds
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/web/
    suffix: .html


#  servlet:
#    multipart:
#      maxFilSize: 10MB
#      maxRequestSize: 15MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

user:
  address_max: 20